const errorMessages = {
 100: "HEADER_IS_MISSING",
  101: "DEVICE_TYPE_NOT_ALLOWED",
  102: "Invalid Api Key",
  103: "A token is required for authentication",
  104: "Invalid token, please login again",
  105: "Validation error",
  106: "Internal server error",
  107: "This email doesn't exist",
  108: "Unauthorised access",
  110: "Invalid genre name",
  111: "Invalid credentials",
  112: "Email Already Exist, Please use a different email",
  113: "Unable send email, Please try again",
  114: "Email sending limit expire",
  115: "Already punched in today",
  123: "Email sent failed",
  124: "Please enter valid code",
  125: "Code already used",
  127: "Invalid user id",
  116: "Punch In required",
  117: "Already punched out today",
  118: "You have enter an Incorrect PIN, Please enter the correct PIN",
  119: "Your account is inactive, Please contact admin",
  120: "This email is registered using google login. Please use that option to sign in.",
  121: "Invalid season id",
  122: "Invalid app type",
  128: "Cannot send request to self",
  129: "Already friends",
  130: "No request found to cancel",
  131: "Already sent request",
  132: "Invalid request id",
  133: "Invalid search Id",
  134: "Date time must be after current time",
  135: "Invalid date id",
  136: "You cannot upload more than five images",
  137: "Invitation already sent to user",
  138: "Date invitation no longer pending",
  139: "Invalid comment id",
  140: "Old password does not matched",
  141: "Interest already exist",
  142: "Invalid event id",
  143: "Invalid interest id",
  144: "Interest in use",
  145: "Comment already deleted",
  146: "No theme data available",
  147: "Event already reported",
  148: "Event request already resolved",
  149: "Invalid artist id",
  150: "Invalid music category id",
  151: "Invalid music type",
  152: "Normal type must have one audio",
  153: "Invalid Music Id",
  154: "Music Not Found",
  155: "Meta Already Exists",
  156: "Meta Not Found",
  157: "Music Approved Successfully",
  158: "Music Disapproved Successfully",
  159: "Invalid Is Approved Value",
  162: "Invalid audio id",
  163: "Audio not found",
  164: "Event already reported",
  171: "Start date should be greater than end date",
  172: "Invalid photo id",
  192: "At least one episode required that's why can't delete last one",
  193: "Access denied for this user",
  200: "SUCCESS",
  400: "BAD_REQUEST_PLEASE_CHECK_YOUR_INPUT",
  404: "RESOURCE_NOT_FOUND",
  500: "Internal server error",
}
export const getErrorMessage = (code) => {
  return errorMessages[code] || "An unexpected error occurred.";
};

